services:
    # PHP Service
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        image: siap-mapan-php
        container_name: siap-mapan-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www:z
            - /usr/local/bin/wkhtmltopdf:/usr/local/bin/wkhtmltopdf:ro
            - /usr/local/bin/wkhtmltoimage:/usr/local/bin/wkhtmltoimage:ro
        networks:
            - siap-mapan-network
            - web-network

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: siap-mapan-nginx
        restart: unless-stopped
        ports:
            - "8005:80"
        volumes:
            - ./:/var/www:z
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:z
        networks:
            - siap-mapan-network
            - web-network
        depends_on:
            - php

networks:
    siap-mapan-network:
        driver: bridge
    web-network:
        external: true

volumes:
    php_framework_cache:
        driver: local
    php_bootstrap_cache:
        driver: local
